### ISSUE TITLE
Use relays when sending stop to the rover

### ISSUE THREAD

**Issue by c2huc2hu** [rsx-utoronto/rover#11]
This prevents the rover from driving backward when no power is being delivered

**Comment by c2huc2hu** [comment]
Demo: Oct 28, along with virtual joystick

**Comment by c2huc2hu** [comment]
# Using relays when sending stop to the rover

## Goal
As an additional safety feature, the relays should cut power to the wheels. 

## Files to modify
- drive_server.js (disable the relays when receiving the stop command)

**Comment by c2huc2hu** [comment]
Relays code is in `aux_server.js` and `auxiliary.ino`. 
Drive code is in `drive_server.js`.

When you get a stop signal in drive server, also disable the relays.

**Comment by c2huc2hu** [comment]
Test procedure: 
- download postman
- send PUT `localhost:8080/drive/stop` through postman 
- verify that the relays are disabled by GET `localhost:8080/aux/`

**Comment by mubtaseemz** [comment]
fixed in ee21952bea38585d1d4e3ec8361bf76b029a05d7
